apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: load-generator
  name: load-generator
spec:
  containers:
    - name: load-generator
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do wget -q -O-  http://php-apache ;  done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
