apiVersion: v1
kind: Namespace
metadata:
  name: phpload

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: phpload
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: sajid2045/phpload:1.1.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: phpload
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  creationTimestamp: "2020-04-13T10:27:50Z"
#  name: php-apache
#  namespace: phpload
#spec:
#  maxReplicas: 10000
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: php-apache
#  targetCPUUtilizationPercentage: 50
