# permissions for end users to view hpatuners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpatuner-viewer-role
rules:
- apiGroups:
  - webapp.streamotion.com.au
  resources:
  - hpatuners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.streamotion.com.au
  resources:
  - hpatuners/status
  verbs:
  - get
