
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
- resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - webapp.streamotion.com.au
  resources:
  - hpatuners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.streamotion.com.au
  resources:
  - hpatuners/status
  verbs:
  - get
  - patch
  - update
