apiVersion: webapp.streamotion.com.au/v1
kind: HpaTuner
metadata:
  name: php-apache-tuner
  namespace: phpload
spec:
  downscaleForbiddenWindowSeconds: 60
  scaleTargetRef:
    kind: HorizontalPodAutoscaler
    name: php-apache
  minReplicas: 1
  maxReplicas: 1000
  useDecisionService: false