apiVersion: webapp.streamotion.com.au/v1
kind: HpaTuner
metadata:
  name: php-apache-tuner-error
spec:
  downscaleForbiddenWindowSeconds: 600
  upscaleForbiddenWindowSeconds: 5
  scaleTargetRef:
    kind: HorizontalPodAutoscaler
    name: php-apache-error
  minReplicas: 2
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50