apiVersion: webapp.streamotion.com.au/v1
kind: HpaTuner
metadata:
  name: php-apache-tuner
spec:
  downscaleForbiddenWindowSeconds: 60
  scaleTargetRef:
    kind: HorizontalPodAutoscaler
    name: php-apache
  minReplicas: 2
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50