apiVersion: webapp.streamotion.com.au/v1
kind: HpaTuner
metadata:
  name: php-apache-tuner
  namespace: phpload
spec:
  downscaleForbiddenWindowSeconds: 60
  cpuIdlingPercentage: 5
  scaleTargetRef:
    kind: HorizontalPodAutoscaler
    name: php-apache
  minReplicas: 10
  maxReplicas: 1000
  useDecisionService: false