dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: streamotion-platform-ops-k8s-hpa-tuner
  repository: file://../helm-release
