# FROM gcr.io/jenkinsxio/builder-maven:latest
# https://d2iq.com/blog/running-kind-inside-a-kubernetes-cluster-for-continuous-integration
#old known jenkins builder-maven working sha(latest they updated helm etc so dont risk it)
FROM gcr.io/jenkinsxio/builder-maven:2.0.1263-602

RUN yum install -y epel-release && \
    yum update -y && \
    yum install -y telnet && \
    yum install python-pip -y && \
    yum install python34-pip -y && \
    pip install --upgrade pip  && \
    yum install -y python34-pip && \
    yum install -y \
      yum-utils \
      device-mapper-persistent-data \
      lvm2 \
      git \
      make \
      curl && \
    yum-config-manager \
      --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
    yum install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io && \
    yum clean all && \
    pip install --upgrade pip && \
    pip install awscli

RUN update-alternatives --set iptables  /usr/sbin/iptables-legacy || true && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true && \
    update-alternatives --set arptables /usr/sbin/arptables-legacy || true

ARG HUB_VERSION=2.12.4
RUN curl -L https://github.com/github/hub/releases/download/v2.12.4/hub-linux-amd64-${HUB_VERSION}.tgz -o /tmp/hub.tar.gz && \
    tar -xvzf /tmp/hub.tar.gz -C /tmp && \
    mv /tmp/hub-linux-amd64-${HUB_VERSION}/ /usr/local/hub && rm -rf /tmp/hub.tar.gz

RUN curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.12.1/skaffold-linux-amd64 && chmod +x skaffold && \
    mv skaffold /usr/local/bin

ENV HELM_VERSION 2.16.10
RUN curl -f https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz  | tar xzv && \
  mv linux-amd64/helm /usr/bin/ && \
  mv linux-amd64/tiller /usr/bin/ && \
  rm -rf linux-amd64

# Set up subuid/subgid so that "--userns-remap=default" works
# out-of-the-box.
RUN set -x && \
    groupadd --system dockremap && \
    adduser --system -g dockremap dockremap && \
    echo 'dockremap:165536:65536' >> /etc/subuid && \
    echo 'dockremap:165536:65536' >> /etc/subgid

VOLUME /var/lib/docker
VOLUME /var/log/docker
EXPOSE 2375 2376
ENV container docker

ARG GO_VERSION=1.15.2
ARG KIND_VERSION=v0.9.0

# replace current go version with 1.15
RUN rm -rf /usr/local/go
RUN rm -rf go
RUN wget https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz
RUN tar -xvf go${GO_VERSION}.linux-amd64.tar.gz
RUN mv go /usr/local

ENV GOPATH /go
ENV PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# install kind
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
RUN chmod +x ./kind
RUN mv ./kind /usr/bin/kind

# install ginkgo
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega/...

#kubectl
RUN touch /root/streamotion


CMD ["mvn","-version"]