apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
    jenkins/streamotion-docker-in-docker: "true"
  name: dind-jenkins-pod
  namespace: jx-test
spec:
  containers:
  - args:
    - cat
    image: XXXX/streamotion-platform-general-docker-generic-builder:0.0.12
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    name: dind
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 500m
        memory: 1Gi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/jenkins/.docker #this is the k8s node docker host jenkins makes available , dont use/touch it
      name: volume-2
    - mountPath: /lib/modules
      name: volume-5
    - mountPath: /var/lib/docker
      name: volume-4
    - mountPath: /root/.m2
      name: volume-1
    - mountPath: /sys/fs/cgroup
      name: volume-6
    - mountPath: /var/run/docker.sock
      name: volume-0
    - mountPath: /home/jenkins/.gnupg
      name: volume-3
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  volumes:
  - hostPath:
      path: /var/run/docker.sock  #this is the k8s node docker host jenkins makes available , dont use/touch it
      type: ""
    name: volume-0
  - name: volume-2
    secret:
      defaultMode: 420
      secretName: jenkins-docker-cfg
  - name: volume-1
    secret:
      defaultMode: 420
      secretName: jenkins-maven-settings
  - emptyDir: {}
    name: workspace-volume
  - emptyDir: {}
    name: volume-4
  - name: volume-3
    secret:
      defaultMode: 420
      secretName: jenkins-release-gpg
  - hostPath:
      path: /sys/fs/cgroup  #needed for dind docker engine
      type: ""
    name: volume-6
  - hostPath:
      path: /lib/modules
      type: ""
    name: volume-5
  - name: jenkins-token-nhgn2
    secret:
      defaultMode: 420
      secretName: jenkins-token-nhgn2
