apiVersion: v1
appVersion: 1.0.14
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: streamotion-platform-ops-k8s-hpa-tuner
version: 1.0.14
